In [1]:
#切片索引
import numpy as np

In [9]:
lst1 = [1,2,3,4,5]
arr1d = np.array(lst1)
print(arr1d)
arr1d[1:4]

[1 2 3 4 5]


array([2, 3, 4])

In [10]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d
print(arr3d)
arr3d[0:1]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[1, 2, 3],
        [4, 5, 6]]])

In [16]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr2d
print(arr2d)
print(arr2d[:2])
print('-'*8)
arr2d[:2, 1:]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
--------


array([[2, 3],
       [5, 6]])

In [20]:
arr2d[2, 1:]

array([8, 9])

In [23]:
arr2d[:2, 2]

array([3, 6])

In [25]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [26]:
#布尔值索引

In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)#使用numpy.random中的randn函数生成一些正态分布的随机数据：
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [28]:
data

array([[ 1.03525906,  0.9285425 ,  1.6920562 , -0.19873868],
       [-1.96901469, -2.90516059, -0.06237482, -0.76501953],
       [-0.102832  , -0.04150852, -0.8781708 ,  1.3554765 ],
       [-2.0331249 , -0.62422881,  0.24422048,  2.64037742],
       [ 2.83397182,  0.93589981, -0.42564395, -0.71888409],
       [-0.55468172, -0.62749028,  0.62325431,  1.66749714],
       [-0.71299559,  0.77560615, -1.33285933,  0.92855377]])

In [29]:
names == 'Bob'
#假设每个名字都对应data数组中的一行，而我们想要选出对应于名字"Bob"的所有行。
#跟算术运算一样，数组的比较运算（如==）也是矢量化的。因此，对names和字符串"Bob"的比较运算
#将会产生一个布尔型数组：

array([ True, False, False,  True, False, False, False])

In [31]:
#这个布尔型数组可用于数组索引：
data[names== 'Bob']
#布尔型数组的长度必须跟被索引的轴长度一致。

array([[ 1.03525906,  0.9285425 ,  1.6920562 , -0.19873868],
       [-2.0331249 , -0.62422881,  0.24422048,  2.64037742]])

In [32]:
#注意：如果布尔型数组的长度不对，布尔型选择就会出错，因此一定要小心。

In [33]:
#下面的例子，我选取了names == 'Bob'的行，并索引了列：

In [36]:
data[names== 'Bob', 2:]

array([[ 1.6920562 , -0.19873868],
       [ 0.24422048,  2.64037742]])

In [41]:
data[names== 'Bob', 3]

array([-0.19873868,  2.64037742])

In [46]:
#要选择除"Bob"以外的其他值，既可以使用不等于符号（!=），也可以通过~对条件进行否定：
names != 'Bob'

data[names != 'Bob'] 
#data[~(names == 'Bob')]

array([[-1.96901469, -2.90516059, -0.06237482, -0.76501953],
       [-0.102832  , -0.04150852, -0.8781708 ,  1.3554765 ],
       [ 2.83397182,  0.93589981, -0.42564395, -0.71888409],
       [-0.55468172, -0.62749028,  0.62325431,  1.66749714],
       [-0.71299559,  0.77560615, -1.33285933,  0.92855377]])

In [48]:
#  ~操作符用来反转条件很好用：
cond = names == 'Bob'
data[~cond]

array([[-1.96901469, -2.90516059, -0.06237482, -0.76501953],
       [-0.102832  , -0.04150852, -0.8781708 ,  1.3554765 ],
       [ 2.83397182,  0.93589981, -0.42564395, -0.71888409],
       [-0.55468172, -0.62749028,  0.62325431,  1.66749714],
       [-0.71299559,  0.77560615, -1.33285933,  0.92855377]])

In [50]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [74]:
print(arr[[0,1,3,5], [2,2,2,2]]) #花式索引(0,2)(1,2)(3,2)(5,2)
print('-'*18)
print(arr[[0,1,3,5]][:,[2]])

[ 2  6 14 22]
------------------
[[ 2]
 [ 6]
 [14]
 [22]]


In [59]:
#选取矩阵的行列子集应该是矩形区域的形式
#arr[[0, 1, 3, 5]][:, [2, 2, 2, 2]]
arr[[0, 1, 3, 5]][:, [0, 1, 3, 2]]

array([[ 0,  1,  3,  2],
       [ 4,  5,  7,  6],
       [12, 13, 15, 14],
       [20, 21, 23, 22]])

In [57]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [75]:
#记住，花式索引跟切片不一样，它总是将数据复制到新数组中。
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

- 转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性：

In [77]:
arr= np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

- 所得到的数组中的每个元素为，第一个矩阵中与该元素行号相同的元素与第二个矩阵与该元素列号相同的元素，两两相乘后再求和。

In [79]:
m = np.arange(1,5).reshape(2,2) 
m

array([[1, 2],
       [3, 4]])

In [80]:
n = np.arange(2,6).reshape(2,2) 
n

array([[2, 3],
       [4, 5]])

In [81]:
np.dot(m,n) # 1*2+2*4=10, 1*3+2*5=13, 3*2+4*4=22, 3*3+4*5=29

array([[10, 13],
       [22, 29]])